### PR TITLE
Move [HTML] and [TC39-MIME-ISSUE] from Normative to Informative

### LINKED ISSUE #5: [TC39-MIME-ISSUE] should be Informative
I believe the reference to TC39's [# 332 - Add `application/javascript+module` mime to remove ambiguity](https://web.archive.org/web/20170814193912/https://github.com/tc39/ecma262/issues/322) does not need to be a normative reference, but instead an informative reference.  According to the [IESG's statement](https://www.ietf.org/iesg/statement/normative-informative.html), a normative reference is one "that must be read to understand or implement the technology"; this issue provides worthwhile context but I don't think it's necessary to read in order to implement `.mjs` module support.

### PR DESCRIPTION
**Pull request by linuxwolf**
Fixes #5

### CODE REVIEW

**Comment by annevk** [comment]
This is wrong. HTML needs to be normative for the encoding bits.

**Comment by linuxwolf** [comment]
@annevk 

This document is carrying forward the `charset` encoding instructions from RFC 4329.  Those look correct to me, and don't seem contradict the WHATWG document.  Can you elaborate why it should be changed?

**Comment by annevk** [comment]
Looking at https://tools.ietf.org/html/rfc4329#section-4.2 step 2 and 1 are reversed these days and step 3 is bogus as far as HTML embedding goes (it defaults to the encoding of the document or an attribute on the `script` element if there's nothing else).

**Comment by linuxwolf** [comment]
I'm looking at https://html.spec.whatwg.org/multipage/scripting.html#concept-script-type, which is what \[HTML\] points to right now.  This doesn't talk about the `charset` parameter on the media type, but the `charset` on the `\<script />` tag.  As such, it still reads as compatible with RFC 4329 § 4.2 to me, so I'm clearly missing something:

* The current reference is bad, or
* something missing/unclear in the referenced specifications; or
* I'm very dense

The \[HTML] reference is turning into a bigger, arguably separate, issue.

**Comment by annevk** [comment]
https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-script (step 21)
https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-script (step 6,7)
https://encoding.spec.whatwg.org/#decode (step 4)

**Comment by linuxwolf** [comment]
@annevk thanks for the pointers.  I'll create an issue to track this concern.

**Pull request merged**
